{{- if .Values.acl.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: gs-cloud-pgconfig-acl-acl-config
type: Opaque
data:
    acl-username: {{ .Values.acl.secrets.acl_username }}
    acl-password: {{ .Values.acl.secrets.acl_password }}
    acl-db-username: {{ .Values.acl.secrets.acl_db_username }}
    acl-db-password: {{ .Values.acl.secrets.acl_db_password }}
    acl-users-admin-password: {{ .Values.acl.secrets.acl_users_admin_password }}
    acl-users-geoserver-password: {{ .Values.acl.secrets.acl_users_geoserver_password }}
{{- end }}